### ISSUE TITLE
v4.0 missing from changelog

### ISSUE THREAD

**Issue by naugtur** [hapijs/qs#102]
Why the version bump if nothing noteworthy changed? Or is it just missing?

**Comment by naugtur** [comment]
And while we're at it - if I update 2.4.2 to 4.0 in `ampersand-sync` will it break things? IE9?

**Comment by AdriVanHoudt** [comment]
https://github.com/hapijs/qs/pull/98
Look for these (https://github.com/hapijs/qs/issues?q=label%3A%22breaking+changes%22+is%3Aclosed) in hapi repos ;)

**Comment by naugtur** [comment]
good tip. thx (changelog still missing, leaving open)

**Comment by AdriVanHoudt** [comment]
I think https://github.com/hapijs/qs/pull/98/files#diff-04c6e90faac2675aa89e2176d2eec7d8 pretty much covers it, qs does not allow to use object prototype names as queryparams by default now (as far as I can deduct) @nlf can clarify maybe

**Comment by naugtur** [comment]
That's what I see in the discussions as well. updating from 2.x to 4.0 seems safe unless you were doing weird things already.

**Comment by AdriVanHoudt** [comment]
jup, unless you allowed stuff like `hasownproperty` as a querystring you should be fine I think
