### ISSUE TITLE
support for comma for stringifying arrays

### ISSUE THREAD

**Issue by tusharmath** [hapijs/qs#112]
Can we have something like —

```javascript
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
// 'a=b,c'
``` 

Does it make sense?

**Comment by hueniverse** [comment]
Seems complicated for no reason. You can already express this structure and it isn't that much more verbose.

**Comment by tusharmath** [comment]
complexity lies when you have multiple params that are needed to be serialized this way.

**Comment by hueniverse** [comment]
This module should add no new features ever. It is already insanely complex.

**Comment by Marsup** [comment]
If you have complex cases, most of the times you're better covered by using POST with a sane JSON serialization.

**Comment by nlf** [comment]
yeah i'm gonna pass on this, sorry.

this module is actually going to become much much simpler soon.

**Comment by eladrof** [comment]
@hueniverse can you please demonstrate how this structure can be expressed?

**Comment by ljharb** [comment]
@eladrof I'm now maintaining the module.

You can provide a custom parsing encoder that can represent an array as a comma-separated string, for example.

**Comment by kaufmann42** [comment]
@ljharb how would that work? Don't see that in the documentation anywhere.

**Comment by ljharb** [comment]
@kaufmann42 look in the docs at "This encoding can also be replaced by a custom encoding method set as encoder option:", that section and the one after it.

**Comment by kaufmann42** [comment]
@ljharb Ah I see. What I'm looking for is to turn something like:

```
params: {
a: ['array', 'of', 'stuff'],
b: ['array', 'of', 'stuff'],
c: ['array', 'of', 'stuff']
}
```

into `?a=array,of,stuff&b=array,of,stuff&c=array,of,stuff`. I don't believe that's possible from that function. Is there any way to do something like this?

**Comment by ljharb** [comment]
@kaufmann42 no, that's what #219 is for tho.
