### ISSUE TITLE
Why always encode the stringified version?

### ISSUE THREAD

**Issue by vvo** [hapijs/qs#116]
Hi, great library.

I do not understand why the default when stringifying is to always encode the URI.

I feel the decision to encode the URI should be left to the user. ALready providing a good deserialization/serialization mechanism is great but then why encodeURIComponent by default?

Encoded URIs are not always what you want and most of the time you do not need to encode them.

When using `.pushState` for example then you do not need to have your querystring in an encoded form.

You only need to encodeURIComponent when you store a query string inside a query string parameter (&query=full query string).

Otherwise there's no need because the browser will already understand it's a query string and if you copy paste the url bar then it will be already encoded, by the browser.

So:
1. What was the decision to encode it by default?
2. Would you accept a PR allowing to disable this behavior (so that we do not have to decodeURIComponent on our side).

Thanks.

**Comment by pho3nixf1re** [comment]
To maintain backwards compatibility it would be nice to leave it encoded by default but have an option to disable it when not needed. Most of the use cases I've came across don't need the encoding. It feels weird having to always wrap this library's output in an `unecode` call.

**Comment by vvo** [comment]
> Most of the use cases I've came across don't need the encoding. It feels weird having to always wrap this library's output in an unecode call.

Ah! Great that we are not alone feeling this. Yes for backward compat we need to stay encoded by default and provide a way to not get the encoded form also.

@nlf @hueniverse Would you accept a PR providing a new API way to do so (stringify without encoding)?

**Comment by nlf** [comment]
working on it

**Comment by nlf** [comment]
closed via 282980a

**Comment by vvo** [comment]
![2015-09-11-192458_250x69_scrot](https://cloud.githubusercontent.com/assets/123822/9821476/d4a9c7d8-58ba-11e5-8cd1-25189a8626c5.png)

![2015-09-11-192505_292x138_scrot](https://cloud.githubusercontent.com/assets/123822/9821478/d606075e-58ba-11e5-860c-87f4642487c4.png)

![6iamwrpf0lmme](https://cloud.githubusercontent.com/assets/123822/9821512/02e5153a-58bb-11e5-9f0a-6d27aa081541.gif)

**Comment by pho3nixf1re** [comment]
Wow! That was... fast. :smile_cat:

**Comment by nik-kor** [comment]
Hi! When will this feature be released, so it will be possible to install it with special version?

**Comment by vvo** [comment]
It was released. Good to know you also needed it

**Comment by nik-kor** [comment]
oh, i got it! https://github.com/hapijs/qs/commit/27ac28f75bc95c6a85552ad709b52ee2cdfb1209 was made after 5.1.0 tag
