### ISSUE TITLE
Qs.parse() has the bug?

### ISSUE THREAD

**Issue by Rabbit0306** [hapijs/qs#121]
Here I use the example in MD.

```
Qs.parse('a.hasOwnProperty=b', { plainObjects: true });
// { a: { hasOwnProperty: 'b' } }
```

But I get the result such as:

```
{ 'a.hasOwnProperty': 'b' }
```
Is any thing wrong?

**Comment by nlf** [comment]
Nothing is wrong. If you're expecting a nested property, you also need to enable the `allowDots` option in your call to parse. That will result in an object like:

```
{ a: { hasOwnProperty: 'b' } }
```

**Comment by Rabbit0306** [comment]
Get it! Thank you for your answer!
