### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by bmtechlab** [hapijs/qs#126]
After [ed1696](https://github.com/hapijs/qs/commit/ed169696b6cebacf8e7f7c6b4ba8eeb5f2cb2694)  commit I have an error:
```
path/to/lib/qs/lib/index.js:5

const Stringify = require('./stringify');
^^^^^
>> Mocha exploded!
>> SyntaxError: Use of const in strict mode.
...
```

I use node v0.10.40.

**Comment by Marsup** [comment]
Use a qs version compatible with your node version.

**Comment by Marsup** [comment]
FYI 5.2.0 was the latest one compatible with the node 0.x serie.
