### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by BHare1985** [hapijs/qs#130]
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\source\<hidden>\node_modules\express\node_modules\connect\lib\middl
eware\bodyParser.js:13:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Your new commit was picked up by my version of `express` which ultimately broke my nodejs app.

If I am not mistaken, this changed broke anyone who uses `express` or at least in a certain configuration that I had (my version, etc)

Running  v0.12.3 and express 2.4.3

**Comment by nlf** [comment]
use node 4.0 or greater. the new major version of qs requires it.

**Comment by hueniverse** [comment]
That's because you are using package.json incorrectly. You need to only get versions you tested with, not just the latest. Learn how semver works!

**Comment by BHare1985** [comment]
I hard coded the express I want, express however used the latest qs. So the issue was out of my hands, FYI.

**Comment by hueniverse** [comment]
@dougwilson ^^^

**Comment by dougwilson** [comment]
The stack trace shows some old version of `express` 3.x, well out of support. I can look if I'm told what version, but I wouldn't be surprised if it's from years ago. We have only used locked dependencies for a long time.

**Comment by dougwilson** [comment]
Nvm, it says "2.4.3" in the post. There is nothing we can do; 2.4.3 came out in summer 2011. Only solution I can say is upgrade to a supported version of Express or use shrinkwap (or check in your `node_modules` folder to source control).

**Comment by bryce-gibson** [comment]
@BHare1985 I believe you might be able to add the qs version you want to your package.json, and then npm will only install the qs version you requested (as the express dependency will be satisfied by the version specified in package.json). (eg adding `"qs": "5.2.0"` to package.json ; then doing a clean npm install)

**Comment by BHare1985** [comment]
Yes I ended up doing what bryce suggested and it works. I  had plans to update express from 2.4.3 but figured why fix something not broken, I guess this gives me more motivation.
