### ISSUE TITLE
package.json main file is es6

### ISSUE THREAD

**Issue by jscheid** [hapijs/qs#132]
Hi,

I have my `node_modules` excluded from babelfication, mostly for performance reasons. This works well with dozens of other packages because pretty much every package on npmjs exposes es5 (or lower) in their distribution. But qs 6.0.0 says `lib/index.js` is the main file, which is es6. I've worked around it by doing

    import qs from "qs/dist/qs";

But in #128 you say that you're going to remove `dist`. It also gives me a warning:

    WARNING in ./~/qs/dist/qs.js
    Critical dependencies:
    1:475-482 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/qs/dist/qs.js 1:475-482

I could work around it in a different way by including qs in the babel loader inclusion patterns, still I think it would generally be cleaner if you could change the build so that the distribution is es5.

**Comment by Marsup** [comment]
Can't you just fix your regexp ?

**Comment by jscheid** [comment]
If you mean the babel-loader inclusion patterns, I could make an exception just for qs... but it would be the only package out of 78 that needs it, so I don't know if "fix" is the right word.

**Comment by Marsup** [comment]
Get used to it, node is evolving to ES6, qs won't be alone very long.

**Comment by jscheid** [comment]
Okay, thanks.

**Comment by Marsup** [comment]
@nlf feel free to intervene if you don't agree ;)

**Comment by arb** [comment]
You can keep your noParse option, and try the resolve-alias webpack option to redirect `require('qs')` to `require('qs/dist/qs')`

**Comment by nlf** [comment]
that's irrelevant when dist goes away :)
