### ISSUE TITLE
Tests use .eslintrc files defined outside the project

### ISSUE THREAD

**Issue by fatfisz** [hapijs/qs#136]
I've run `npm test` and found out that there are a lot of errors. After looking around for a bit I've found the culprit - the `.eslintrc` file defined in the root directory. After changing its name to something else so that ESLint ignores my global rules, tests completed without issues.

Shouldn't there be an `.eslintrc` file in the root of the project so that stuff like this won't happen?

**Comment by nlf** [comment]
the config that's used here is provided by lab, so we don't bother including it in the root of the project. i'm not sure i follow how it is that your eslint config took over from that one, however, as i'm pretty sure lab is designed to use its built in config whenever there isn't an `.eslintrc` in the root of the project.

**Comment by fatfisz** [comment]
Well, I'm not sure what is happening either :/

But the fact is - tests don't work when there is `.eslintrc` in my root dir, and they do work when there is no such file.

**Comment by nlf** [comment]
what do you mean by root dir? like literally at `/.eslintrc`?

**Comment by gergoerdosi** [comment]
In which directory do you execute tests? And what is the command you use?

**Comment by fatfisz** [comment]
I'm in the project directory, where I fire `npm test`.

Placing my `.eslintrc` in the project's parent dir, parent's parent dir, and so on (including the root dir - I'm on Windows, so it's more like `D:\.eslintrc`), causes some linting errors.

**Comment by nlf** [comment]
throwing this upstream to lab https://github.com/hapijs/lab/issues/488
