### ISSUE TITLE
Using let keyword in your source code is breaking firefox

### ISSUE THREAD

**Issue by JosephShering** [hapijs/qs#141]

**Comment by AdriVanHoudt** [comment]
either use a previous version or compile it with something like Babel

**Comment by AndersDJohnson** [comment]
Was this fixed in reverting 6c70b3110ef693cdf187ce4b89c5c10c987a6a32 (use `let` and `const`) via 224c8af8fc8abf48fd9ded33a38997a1d942c1c1?

**Comment by ljharb** [comment]
@AndersDJohnson yes, that's correct.
