### ISSUE TITLE
UglifyJS Error

### ISSUE THREAD

**Issue by jasonadt** [hapijs/qs#144]
After updating to the latest qs version (6.0.1) I noticed the following error when attempting to bundle my app with WebPack:

``` 
ERROR in bundle.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/qs/lib/utils.js:14,0]
```

I'm not sure whether this needs to be fixed by qs or by UglifyJS

Thank you very much!
Jason

**Comment by arb** [comment]
The UglifyJS plugin doesn't understand ES6 features yet is my guess. Make sure you are transpiling QA in your webpack config.

**Comment by Marsup** [comment]
Or go back to a version that's supported on your environment.

**Comment by uditalias** [comment]
+1
