### ISSUE TITLE
merge fails to overwrite properties

### ISSUE THREAD

**Issue by mhils** [hapijs/qs#67]
Hi there,

I stumbled upon this in https://github.com/rackt/react-router/pull/599 - I cannot override properites using `lib/utils:merge`:

```javascript
> merge({a:'a'}, {a:'b'})
{ a: 'a' }

// triggers different code path 
// https://github.com/hapijs/qs/blob/9250c4cda5102fcf72441445816e6d311fc6813d/lib/utils.js#L25
> merge({a:'a'}, {a:undefined}) 
{ a: 'a' }
```

Is this desired behaviour? If not, any idea for a workaround?

Thanks!
Max

**Comment by nlf** [comment]
I'm not sure why you're trying to use the merge method from this directly, as that's not intended usage at all and is not supported.

If you need a `merge` function, you should look at something like [hoek](https://github.com/hapijs/hoek), [underscore](http://underscorejs.org), [lodash](http://lodash.com), or [amp](http://amp.ampersandjs.com/#amp-merge)
