### ISSUE TITLE
Bad parse when turning array into object

### ISSUE THREAD

**Issue by dougwilson** [hapijs/qs#74]
The following shows that when a key starts as an array, values that match `Object.prototype` keys are basically treated as if they are just an empty bracket for some reason. I would not expect the `1` property to exist in the example below:

```
$ node -pe 'require("qs").parse("a[]=b&a[hasOwnProperty]=c&a[x]=y")'
{ a: { '0': 'b', '1': 'c', x: 'y' } }

$ node -pe 'require("qs/package").version'
2.4.1
```

**Comment by dougwilson** [comment]
And the following parse is even more bizarre:
```
$ node -pe 'require("qs").parse("a[]=b&a[t]=u&a[hasOwnProperty]=c")'
{ a: { '0': 'b', t: 'u', c: true } }
```

**Comment by nlf** [comment]
this is related to #80
