### ISSUE TITLE
Perf boost

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/qs#77]
io.js 1.6.0 landed a perf boost for parse and stringify maybe worth taking a look at? https://github.com/iojs/io.js/pull/847

**Comment by nlf** [comment]
the encode method for stringifying had a substantial impact, nothing else really applies to our code base. still, was worth looking, thanks!

**Comment by AdriVanHoudt** [comment]
So did you change anything? Else this issue can be closed.

**Comment by nlf** [comment]
I did, I incorporated the encode method. Working on writing some additional tests.

**Comment by AdriVanHoudt** [comment]
OK cool, glad I could help, certainly for something that is used a lot even
a small perf gain can do a lot in the long run
