### ISSUE TITLE
Option to dedupe multiple keys with the same name

### ISSUE THREAD

**Issue by RGBboy** [hapijs/qs#82]
I couldn't find it in the readme but does this module support deduping params?

I was expecting if I send a=true&a=false I would get a: 'false'

But currently I get a: [ 'true', 'false']

Is this something qs supports? If not would you be open to supporting it?

**Comment by Marsup** [comment]
This is how parsing is supposed to be done AFAIK.

**Comment by RGBboy** [comment]
@Marsup as in it should get set to `'false'`? Or the other way?

**Comment by Marsup** [comment]
If you have multiple parameters with the same name, it should become an array.

**Comment by RGBboy** [comment]
Yep that is what happens currently. However some parsers would deduplicate this and just set it to the last defined value. For example parsing JSON does this if you define a property twice.

Would you be open to a pull request to add this functionality behind an option?

**Comment by Marsup** [comment]
I don't think parsers for other formats are relevant here, look at the other query string parsers, all the ones I know do that.

I'll let @nlf decide on that behavior change but I think it'll be a no.

**Comment by RGBboy** [comment]
Here is my use case if that helps justify the change:

I have an html form with a checkbox. Because browsers only pass the value of a checkbox if it is checked I also have a hidden input to set the unchecked value. This hidden input uses the same name as the checkbox input. When this data is then parsed by qs I get an array, not a single value which is what I would like.

**Comment by Marsup** [comment]
Bad design IMHO. If the value is missing, default to false.

**Comment by RGBboy** [comment]
Not if you have to cater for true, false and undefined.

**Comment by Marsup** [comment]
Then preprocess the query you're sending, but not with some tricks with hidden fields. It's not the server side that needs fixing.

**Comment by RGBboy** [comment]
Unfortunately I can't preprocess because we must cater for clients with no Javascript. Unfortunately the W3C spec forces developers down this road if they want to use checkboxes. If we could use Javascript I would just send JSON and not use query strings at all.

**Comment by Marsup** [comment]
Then why not radio buttons ? Tri-state checkbox in pure html don't exist, the only way to set it is through javascript, so no js, no tri-state. If your user has no possibility to set it himself, I don't see how this can make a difference between "false" and "never been touched false".

**Comment by RGBboy** [comment]
That is true for a single form, but not for multiple with the same endpoint. When a user submits a form with no checkbox we receive undefined (which we interpret as no change) where as if we receive true or false we update the value given.

**Comment by Marsup** [comment]
Then what about not using the same name and default to it with joi (considering you're using it), like :
```js
var schema = Joi.object().keys({
  a: Joi.string().default(Joi.ref('adefault')),
  adefault: Joi.string()
});
```

**Comment by nlf** [comment]
I tend to agree that this shouldn't be `qs`'s problem, it providing the server with *all* passed in parameters is the idea. I don't really like the idea of adding in options for edge cases, especially where a little extra processing after the parsing is done is not much work in your app.

**Comment by nlf** [comment]
Closing this unless there ends up being more demand for it
