### ISSUE TITLE
arrayLimit is surprising behaviour

### ISSUE THREAD

**Issue by ygt-mikekchar** [hapijs/qs#95]
OK.  It's my fault for not reading the documentation closely enough :-)  I just find that having results put in either an array or an object depending on the number of items they contain is incredibly surprising.  Is this a feature that anybody uses?

When I receive the parameters there seems to be no easy way for me to know if the request had more than arrayLimit values.  The only sensible option seems to be to always set arrayLimit to 0.

My personal preference would be to have an option to always put the values in an array or always put the values in an object.  To be honest, it makes absolutely no difference to me which one it is (although I think that iterating over the keys of an object is slightly more computationally intensive).

**Comment by nfroidure** [comment]
:+1: took us a while to understand what was going on, couldn't guess such feature would have been added.

Looks pretty wieird, is it for security reasons or something?

**Comment by AdriVanHoudt** [comment]
not sure what exactly but its security related, @nlf probably knows more

**Comment by nfroidure** [comment]
related https://github.com/hapijs/qs/issues/18 . Can't figure out wich security issue it covers.

**Comment by AdriVanHoudt** [comment]
`The depth limit helps mitigate abuse when qs is used to parse user input, and it is recommended to keep it a reasonably small number.` pretty vague I know :P

**Comment by nfroidure** [comment]
PS: if it really is security related, i assume that throwing an exception is a better behavior than silently change things into something else. I prefer send a 4XX error with good reasons than changing API customers expectations.

**Comment by AdriVanHoudt** [comment]
depends, the docs state it so you can handle to it and in that case it is not a security issue

**Comment by nfroidure** [comment]
Yep but it adds extra work, by example, if i expect answers to be an Array, i'll have to check if answers really is an array an than throw an exception. If i have recurrent data structures, i can really become tricky.

On the other hand, why would i get datas whith a different structure than the one the client sent/i need?

Definitely better to throw an exception imo.

**Comment by nfroidure** [comment]
Here is a PR in case you feel ok with that statement https://github.com/hapijs/qs/pull/96 . Will need a major version bump though.

**Comment by nfroidure** [comment]
Just about the security issue, i think it probably is due to the fact that, array size is limited and a too big size would cause an exception to be thrown:
```js
new Array(Number.MAX_VALUE)
// VM289:2 Uncaught RangeError: Invalid array length
//    at <anonymous>:2:17
//    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
//    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
//    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

You also could get a maximum call stack size using nested forEach/map/filter array methods.

**Comment by nlf** [comment]
That is, in fact, the security issue. The parsing being changed rather than throwing an error is because this isn't always a fail condition, some people are aware of the security concern and accept the fact that they may have to read an object rather than an array to mitigate it. Throwing an error is a bit harsh for most situations.
