### ISSUE TITLE
Changelog update?

### ISSUE THREAD

**Issue by wavded** [hapijs/qs#99]
Curious what was breaking in 4.0.0

Thanks much!

**Comment by hueniverse** [comment]
How about look at the 4.0.0 milestone. Can't be too hard.

**Comment by wavded** [comment]
@hueniverse your comment comes off condescending, if that wasn't the intent, i apologize.  After checking the commits, the changelog and the releases pages I didn't think to look at the milestones.  If that's how you should get up to speed on changes, perhaps removing the changelog and pointing people to the milestones in the readme instead?
